import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#F6F7FC',
    },
    header: {
      flexDirection: 'row',
      backgroundColor: '#fff',
      paddingVertical: 14,
      paddingHorizontal: 16,
      borderBottomWidth: 1,
      borderBottomColor: '#E1E1E1',
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#4A90E2',
    },
    scrollViewContent: {
      flexGrow: 1,
      paddingVertical: 10,
    },
    itemRow: {
      backgroundColor: 'white',
      borderRadius: 8,
      marginBottom: 10,
      marginHorizontal: 10,
      padding: 12,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 2,
    },
    itemHeader: {
      marginBottom: 8,
    },
    itemName: {
      fontSize: 16,
      fontWeight: '600',
      textAlign: 'right',
      color: '#333',
    },
    barcodeText: {
      fontSize: 13,
      color: '#666',
      textAlign: 'right',
    },
    contentRow: {
      flexDirection: 'row-reverse',
      alignItems: 'center',
    },
    imageContainer: {
      width: 70,
      height: 70,
      backgroundColor: '#f5f5f5',
      borderRadius: 6,
      justifyContent: 'center',
      alignItems: 'center',
      marginLeft: 12,
    },
    productImage: {
      width: '100%',
      height: '100%',
      borderRadius: 6,
    },
    placeholderText: {
      color: '#999',
      fontSize: 10,
    },
    noImageContainer: {
      width: 70,
      height: 70,
      backgroundColor: '#E8E8E8',
      borderRadius: 6,
      justifyContent: 'center',
      alignItems: 'center',
    },
    detailsContainer: {
      flex: 1,
    },
    quantitySection: {
      marginBottom: 8,
      backgroundColor: '#f9f9f9',
      borderRadius: 6,
      padding: 8,
    },
    quantityRow: {
      flexDirection: 'row-reverse',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 6,
    },
    lastRow: {
      marginBottom: 0,
    },
    quantityLabel: {
      fontSize: 13,
      color: '#666',
      textAlign: 'right',
    },
    quantityValue: {
      fontSize: 14,
      fontWeight: '500',
      color: '#333',
      marginRight: 8,
    },
    inputQuantity: {
      height: 36,
      width: 70,
      borderWidth: 1,
      borderColor: '#D1D1D1',
      borderRadius: 6,
      paddingHorizontal: 8,
      backgroundColor: '#fff',
      textAlign: 'center',
      fontSize: 14,
    },
    priceSection: {
      marginTop: 8,
    },
    priceRow: {
      flexDirection: 'row-reverse',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 6,
    },
    priceLabel: {
      fontSize: 13,
      color: '#666',
      textAlign: 'right',
    },
    priceInputContainer: {
      flexDirection: 'row-reverse',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: '#D1D1D1',
      borderRadius: 6,
      paddingHorizontal: 8,
      backgroundColor: '#fff',
      height: 36,
      width: 90,
    },
    priceInput: {
      flex: 1,
      textAlign: 'center',
      fontSize: 14,
      paddingVertical: 0,
    },
    currencySymbol: {
      fontSize: 14,
      marginLeft: 2,
      color: '#333',
    },
    subtotalContainer: {
      flexDirection: 'row-reverse',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingTop: 8,
      borderTopWidth: 1,
      borderTopColor: '#F0F0F0',
      marginTop: 8,
    },
    subtotalLabel: {
      fontSize: 14,
      fontWeight: 'bold',
      color: '#4A90E2',
    },
    subtotalValue: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#4A90E2',
    },
    footer: {
      backgroundColor: 'white',
      padding: 16,
      borderTopWidth: 1,
      borderTopColor: '#E5E7EB',
      elevation: 3,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -2 },
      shadowOpacity: 0.1,
      shadowRadius: 3,
    },
    totalContainer: {
      flexDirection: 'row-reverse',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
    },
    totalLabel: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#333',
    },
    totalInputContainer: {
      flexDirection: 'row-reverse',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: '#D1D1D1',
      borderRadius: 6,
      paddingHorizontal: 8,
      backgroundColor: '#fff',
      height: 40,
      width: 120,
    },
    totalInput: {
      flex: 1,
      textAlign: 'center',
      fontSize: 16,
      fontWeight: 'bold',
      paddingVertical: 0,
    },
    attachInvoiceButton: {
      flexDirection: 'row-reverse',
      backgroundColor: '#F0F0F0',
      borderRadius: 8,
      padding: 12,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 12,
    },
    attachButtonText: {
      color: '#333',
      fontSize: 14,
      marginRight: 8,
    },
    confirmButton: {
      flexDirection: 'row',
      backgroundColor: '#4A90E2',
      height: 44,
      borderRadius: 8,
      justifyContent: 'center',
      alignItems: 'center',
    },
    confirmButtonText: {
      color: 'white',
      fontSize: 16,
      fontWeight: 'bold',
    },
    disabledButton: {
      backgroundColor: '#B0B0B0',
    },
    invoiceAttachedContainer: {
      backgroundColor: '#E8F4FF',
      borderRadius: 6,
      padding: 8,
      flexDirection: 'row-reverse',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
    },
    invoiceAttachedText: {
      color: '#4A90E2',
      fontSize: 14,
    },
    removeButton: {
      backgroundColor: '#F0F0F0',
      borderRadius: 4,
      padding: 4,
    },
    removeButtonText: {
      color: '#666',
      fontSize: 12,
    },
    backButton: {
      position: 'absolute',
      left: 15,
      top: '50%',
      transform: [{ translateY: -12 }],
      zIndex: 10,
    },
    placeholder: {
      width: 24,
      height: 24,
    },
    buttonIcon: {
      marginRight: 8,
    },
    statusMessageContainer: {
      position: 'absolute',
      bottom: 20,
      left: '50%',
      transform: [{ translateX: -150 }],  // Half of the width
      backgroundColor: '#4A90E2',
      borderRadius: 6,
      padding: 8,
      zIndex: 10,
      width: 300,
      alignItems: 'center',
    },
    statusMessage: {
      color: 'white',
      fontSize: 14,
      textAlign: 'center',
    }
});