import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      flexDirection: 'row-reverse',
      backgroundColor: '#F6F7FC',
    },
    mainContent: {
      flex: 1,
    },
    header: {
      flexDirection: 'row-reverse',
      alignItems: 'center',
      padding: 16,
      borderBottomWidth: 1,
      borderBottomColor: '#E1E1E1',
    },
    headerTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#4A90E2',
      marginRight: 16,
    },
    formContainer: {
      padding: 24,
      backgroundColor: 'white',
      margin: 16,
      borderRadius: 12,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    inputRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 16,
    },
    halfInput: {
      width: '48%',
      height: 50,
      borderWidth: 1,
      borderColor: '#D1D1D1',
      borderRadius: 8,
      paddingHorizontal: 16,
      textAlign: 'right',
    },
    input: {
      height: 50,
      borderWidth: 1,
      borderColor: '#D1D1D1',
      borderRadius: 8,
      paddingHorizontal: 16,
      marginBottom: 16,
      textAlign: 'right',
    },
    dropdownContainer: {
        backgroundColor: 'white',
        borderRadius: 8,
        paddingHorizontal: 16,
        height: 50,
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#D1D1D1',
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
      },
      placeholder: {
        fontSize: 16,
        color: '#999',
        textAlign: 'right',
        writingDirection: 'rtl',
      },
      selectedText: {
        fontSize: 16,
        color: '#333',
        textAlign: 'right',
        writingDirection: 'rtl',
      },
    button: {
      backgroundColor: '#4A90E2',
      height: 50,
      borderRadius: 8,
      justifyContent: 'center',
      alignItems: 'center',
    },
    buttonText: {
      color: 'white',
      fontSize: 16,
      fontWeight: 'bold',
    },
  });